name: Scan Devcontainer Image

on:
  push: null
  pull_request: null

jobs:
  scan-devcontainer:
    name: Scan Devcontainer Image

    permissions:
      actions: read
      security-events: write

    uses: Vianpyro/Template/.github/workflows/docker-image-verification.yml@docs
    with:
      image_name: devcontainer
      dockerfile_path: ./Dockerfile
      context: .devcontainer
