name: Reusable Docker Image Build and Scan

permissions:
  contents: read

on:
  workflow_call:
    inputs:
      image_name:
        description: 'The name of the Docker image'
        required: true
        type: string
      dockerfile_path:
        description: 'Path to the Dockerfile'
        required: false
        type: string
        default: './Dockerfile'
      context:
        description: 'Build context for Docker'
        required: false
        type: string
        default: '.'

jobs:
  build-and-scan:
    name: Build and Scan ${{ inputs.image_name }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image and load
        uses: docker/build-push-action@v6
        with:
          context: ${{ inputs.context }}
          load: true
          tags: ${{ inputs.image_name }}:latest

      - name: Scan for vulnerabilities
        uses: crazy-max/ghaction-container-scan@v3
        with:
          image: ${{ inputs.image_name }}:latest
          dockerfile: ${{ inputs.dockerfile_path }}
          severity_threshold: HIGH
